### ISSUE TITLE
Prefactorization of Q

### ISSUE THREAD

**Issue by Oscar-Liang** [alecjacobson/computer-graphics-mass-spring-systems#11]
I'm doing the step for each simulation, and I feel like I'm doing something wrong. Because of the pinned vertices, the matrix that is transformed into LLT is different in every iteration. What I end up doing is reverting Q back into its original matrix, adding the result of the penalty method, and then turning *that* into LLT form. My output looks correct, though. Am I misunderstanding how this is done?

**Comment by abhimadan** [comment]
Take a closer look at the penalty term. There is a quadratic term and a linear term, and the quadratic term's "coefficient" (the matrix in the middle) only depends on the pinning matrix C. The pinned vertices don't change so this term is constant.

Recomputing Q isn't technically wrong though, and factoring a, for example, 5000x5000 matrix won't slow down things too much, so that's probably why your results don't look incorrect.
