### ISSUE TITLE
how many iterators should I use for fast_mass_springs_step_dense

### ISSUE THREAD

**Issue by s99090** [alecjacobson/computer-graphics-mass-spring-systems#13]
in the header file, it says to conduct a single step. However, in the read me, it mentioned about 50 iterators for a satisfying result, as well as in the .c file, it has a for-loop for 50 iterators.
I am currently debugging my code, and it did make the result different. I wonder how many iterators I should use for this function.

**Comment by s99090** [comment]
from my understanding, the number of iterators should not matter, it just speeds up the animation, isn't it?

**Comment by alecjacobson** [comment]
Not quite. The number of iterations controls how well we're solving the
energy minimization problem for a given time-step. So fewer iterations will
lead to a less accurate solution.

This can be difficult to notice because in this case "less accurate" just
means that the solution for t+∆t will look more and more like the previous
solution at time t. So fewer iterations will *appear* to slow-down or
"dampen" the solution. The single-spring is a good example. If you do fewer
iterations it will not swing back and forth (even slowly). It will just
come to rest downward as if its embedded in peanut butter.

**Comment by s99090** [comment]
Thank you for the explanation! I observed what you said when I set it to 1 iterator. However, when I set it to a higher number of iterators (50 iterators), the animation goes crazy, feels like there is an arbitrary force exerted on the object. For example, for the trap one, it opens nicely and stays for 5 seconds, but then, it starts to spinning. For the horizontal chain, it never stops and keeps vibrating at the bottom, and when I toggle the wind, it even goes above the pinned vertices.

According to the examples, could you please give some hints about where might go wrong in the code? I am stuck here.

For the others (net, single spring), they are all good but much faster than the ones in the readme.html
For the eiffel, it is good.

**Comment by abhimadan** [comment]
Try running your code with a debugger. If you press spacebar (in the viewer, not the debugger), you can take a single time step through the simulation, so you can keep doing this until you reach the point of the simulation where you feel things start to go wrong.

**Comment by s99090** [comment]
Thanks so much for the help!
